name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: iszzy0wijesinghe
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Colombo
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_topics: yes
          plugin_music: yes
          plugin_music_provider: apple
